
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-trial-jayanth-2-xenial-static
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: eks-trial-jayanth-2
    namespace: default
  project: default
  source:
    repoURL: https://github.com/pmaru-p9/arlon-test.git
    path: clusters/eks-trial-jayanth-2/workload/xenial-static
    targetRevision: HEAD
